# Autogenerated wrapper script for FLTK_jll for aarch64-apple-darwin
export libfltk, libfltk_forms, libfltk_gl, libfltk_images

using Fontconfig_jll
using FreeType2_jll
using JpegTurbo_jll
using libpng_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("FLTK")
JLLWrappers.@declare_library_product(libfltk, "@rpath/libfltk.1.3.dylib")
JLLWrappers.@declare_library_product(libfltk_forms, "@rpath/libfltk_forms.1.3.dylib")
JLLWrappers.@declare_library_product(libfltk_gl, "@rpath/libfltk_gl.1.3.dylib")
JLLWrappers.@declare_library_product(libfltk_images, "@rpath/libfltk_images.1.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Fontconfig_jll, FreeType2_jll, JpegTurbo_jll, libpng_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libfltk,
        "lib/libfltk.1.3.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfltk_forms,
        "lib/libfltk_forms.1.3.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfltk_gl,
        "lib/libfltk_gl.1.3.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfltk_images,
        "lib/libfltk_images.1.3.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
